id: I4EAF3A9E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:04:57+00:00'
last_modified: '2022-06-08T09:42:29.495940+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01048
  title: གསུང་ཐོར་བུ། ངག་དབང་རིན་ཆེན་བཟང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DB46:
      image_group_id: I1CZ818
      title: ''
      total_pages: 420
      order: 1
      base_file: DB46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
